"""add organization_id to purchase_orders

Revision ID: 1ea48aa3d122
Revises: a1c063eee8a5
Create Date: 2026-05-14 12:21:22.822894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea48aa3d122'
down_revision: Union[str, Sequence[str], None] = 'a1c063eee8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'organization_id')
    # ### end Alembic commands ###
