"""add user_id to cashbook

Revision ID: 499f5c3f73ad
Revises: 7a3ba9d74488
Create Date: 2026-05-14 13:22:27.722530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499f5c3f73ad'
down_revision: Union[str, Sequence[str], None] = '7a3ba9d74488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashbook_entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cashbook_entries', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cashbook_entries', type_='foreignkey')
    op.drop_column('cashbook_entries', 'user_id')
    # ### end Alembic commands ###
