"""add organization_id to bills

Revision ID: 7a3ba9d74488
Revises: 1ea48aa3d122
Create Date: 2026-05-14 12:49:10.973949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3ba9d74488'
down_revision: Union[str, Sequence[str], None] = '1ea48aa3d122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bills', 'organizations', ['organization_id'], ['id'])
    op.alter_column('purchase_orders', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'organization_id')
    # ### end Alembic commands ###
