"""add vendor status

Revision ID: d2323d26fdcb
Revises: 24f0d3f0ba55
Create Date: 2026-05-07 17:40:04.622502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2323d26fdcb'
down_revision: Union[str, Sequence[str], None] = '24f0d3f0ba55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'vendors',
    sa.Column(
        'status',
        sa.Enum(
            'PAID',
            'UNPAID',
            'OVERDUE',
            name='vendorstatus'
        ),
        nullable=False,
        server_default='UNPAID'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'status')
    # ### end Alembic commands ###
